name: DND Blogs RSS Collection

on:
  # schedule:
  #  - cron: '0 0 * * *'  # Run every 12 hours
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  collect_rss:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install feedparser requests

    - name: Run RSS collection script
      env:
        DNDBLOGS_GIST_TOKEN: ${{ secrets.DNDBLOGS_GIST_TOKEN }}
        SQUABBLR_TOKEN: ${{ secrets.DNDBLOGS_SQUABBLR_TOKEN }}
        DNDBLOGS_GIST_TRACKER: ${{ secrets.DNDBLOGS_GIST_TRACKER }}
        DNDBLOGS_GIST_DETAILS: ${{ secrets.DNDBLOGS_GIST_DETAILS }}
      run: python dndblogs_rss_collection.py
