name: Politics RSS Collection

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Run daily at midnight (commented out for testing)
  workflow_dispatch:

jobs:
  collect-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # or the version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
          pip install lxml  # if you decide to use lxml as the parser

      - name: Run RSS collection script
        run: python politics_rss_collection.py
        env:
          POL_GIST_TOKEN: ${{ secrets.DNDBLOGS_GIST_TOKEN }}
